# Generated by Django 4.2.7 on 2023-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('doby', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(upload_to='', verbose_name='превью')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='просмотры')),
                ('view_count', models.IntegerField(default=0, verbose_name='просморы')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
