# Generated by Django 4.2.7 on 2023-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_doby_blog_body_remove_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата публикации'),
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='просморы'),
        ),
    ]
