# Generated by Django 4.2.7 on 2023-12-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версию', 'verbose_name_plural': 'Версии'},
        ),
        migrations.RenameField(
            model_name='version',
            old_name='product_name',
            new_name='product',
        ),
    ]
